Repository asleepysheepy/columbus_tip_jars, pull requests merged in 2020-04, with the labels that each got.

#9 Initial Rails configuration and add User/AuthToken models
  server/.env
  server/.rspec
  server/Gemfile
  server/Gemfile.lock
  server/app/models/auth_token.rb
  server/app/models/user.rb
  server/config/application.rb
  server/config/database.yml
  server/db/migrate/20200409205607_create_users.rb
  server/db/migrate/20200409205625_create_auth_tokens.rb
  server/db/schema.rb
  server/spec/factories/auth_tokens.rb
  server/spec/factories/users.rb
  server/spec/models/auth_token_spec.rb
  server/spec/models/user_spec.rb
  server/spec/rails_helper.rb
  server/spec/spec_helper.rb
  server/spec/support/database_cleaner.rb
Labels: Back End, enhancement

#11 Add MaterialUI and set up the document structure
  web/.eslintrc.js
  web/next.config.js
  web/package.json
  web/pages/index.js
  web/src/pages/_app.js
  web/src/pages/_document.js
  web/src/pages/index.js
  web/src/utils/theme.js
  web/yarn.lock
Labels: Front End

#10 Add Register Endpoint
  server/app/controllers/api/v1/auth_controller.rb
  server/app/controllers/api_controller.rb
  server/app/services/authentication_service.rb
  server/config/routes.rb
  server/spec/rails_helper.rb
  server/spec/requests/auth_request_spec.rb
  server/spec/support/json_helper.rb
Labels: Back End, enhancement

#12 sets the port for the next server
  web/package.json
Labels: Front End

#14 add jest and testing library
  web/babel.config.js
  web/jest.config.js
  web/package.json
  web/test/pages/index-test.js
  web/test/setup-tests.js
  web/yarn.lock
Labels: Front End

#13 Add rubocop to Rails api
  server/.rubocop.yml
  server/Gemfile
  server/Gemfile.lock
  server/Rakefile
  server/app/controllers/api/v1/auth_controller.rb
  server/app/controllers/api_controller.rb
  server/app/mailers/application_mailer.rb
  server/app/models/auth_token.rb
  server/app/models/user.rb
  server/app/services/authentication_service.rb
  server/config.ru
  server/config/application.rb
  server/config/boot.rb
  server/config/environment.rb
  server/config/environments/development.rb
  server/config/environments/production.rb
  server/config/environments/test.rb
  server/config/initializers/assets.rb
  server/config/routes.rb
  server/spec/rails_helper.rb
  server/spec/requests/auth_request_spec.rb
  server/spec/spec_helper.rb
  server/spec/support/database_cleaner.rb
Labels: Back End, enhancement

#17 Add /api/v1/auth/me and /api/v1/auth/login routes
  server/app/controllers/api/v1/auth_controller.rb
  server/app/controllers/api_controller.rb
  server/app/services/authentication_service.rb
  server/config/locales/en.yml
  server/config/routes.rb
  server/spec/factories/auth_tokens.rb
  server/spec/rails_helper.rb
  server/spec/requests/auth_request_spec.rb
  server/spec/support/auth_helper.rb
Labels: Back End

#21 Delete package-lock.json in favor of the yarn.lock file
  web/package-lock.json
Labels: Front End, enhancement

#22 Setup CORS and clean up unused Railties
  server/Gemfile
  server/Gemfile.lock
  server/config/application.rb
Labels: Back End, enhancement

#23 Add a docker-compose file for the server
  server/docker-compose.yml
Labels: Back End, enhancement

#24 Scaffold out data model
  server/app/models/business_profile.rb
  server/app/models/business_user_profile.rb
  server/app/models/donation_method.rb
  server/app/models/user.rb
  server/app/models/user_profile.rb
  server/db/migrate/20200410155318_create_user_profiles.rb
  server/db/migrate/20200410155803_create_business_profiles.rb
  server/db/migrate/20200410160129_create_business_user_profiles.rb
  server/db/migrate/20200410160731_create_donation_methods.rb
  server/db/schema.rb
  server/spec/factories/business_profiles.rb
  server/spec/factories/business_user_profiles.rb
  server/spec/factories/donation_methods.rb
  server/spec/factories/user_profiles.rb
  server/spec/models/business_profile_spec.rb
  server/spec/models/business_user_profile_spec.rb
  server/spec/models/donation_method_spec.rb
  server/spec/models/user_profile_spec.rb
  server/spec/models/user_spec.rb
Labels: Back End

#27 Update the mui theme to use the secondary color and font from brand guide lines
  web/src/pages/_document.js
  web/src/utils/theme.js
Labels: Front End

#25 Sets up both login and registration w/ API call
  web/src/pages/login.js
  web/src/pages/register.js
  web/src/utils/form-errors.js
Labels: Front End

#32 Add eslint rule to force space inside curly braces
  web/.eslintrc.js
  web/src/pages/login.js
  web/src/pages/register.js
  web/src/utils/form-errors.js
Labels: Front End

#29 Create BusinessProfilesController
  server/app/controllers/api/v1/business_profiles_controller.rb
  server/app/controllers/api_controller.rb
  server/app/models/business_profile.rb
  server/app/models/state.rb
  server/app/services/profile_service.rb
  server/db/migrate/20200410194005_remove_drop_zip_from_business_profiles.rb
  server/db/migrate/20200410194109_add_string_zip_to_business_profiles.rb
  server/db/schema.rb
  server/spec/factories/business_profiles.rb
  server/spec/requests/business_profile_request_spec.rb
Labels: Back End, enhancement

#33 Change up material imports
  web/babel.config.js
  web/package.json
  web/src/pages/_app.js
  web/src/pages/login.js
  web/src/pages/register.js
  web/yarn.lock
Labels: Front End, enhancement

#34 Add user profile controller and service
  server/Gemfile
  server/Gemfile.lock
  server/app/controllers/api/v1/user_profiles_controller.rb
  server/app/services/profile_service.rb
  server/spec/requests/user_profile_request_spec.rb
Labels: Back End

#35 Add DonationMethods controller
  server/app/controllers/api/v1/donation_methods_controller.rb
  server/app/models/business_profile.rb
  server/app/models/donation_method.rb
  server/app/models/user_profile.rb
  server/spec/factories/donation_methods.rb
  server/spec/models/business_profile_spec.rb
  server/spec/models/donation_method_spec.rb
  server/spec/models/user_profile_spec.rb
  server/spec/requests/donation_methods_request_spec.rb
Labels: Back End

#36 add a nav component
  .gitignore
  web/package.json
  web/public/looking-good-cbus.png
  web/public/zeit.svg
  web/src/components/nav/app-bar.js
  web/src/components/nav/drawer.js
  web/src/components/nav/index.js
  web/src/pages/_app.js
  web/yarn.lock
Labels: Front End, enhancement

#37 add AuthContext
  web/.env
  web/jest.config.js
  web/next.config.js
  web/package.json
  web/src/components/nav/app-bar.js
  web/src/components/nav/drawer.js
  web/src/contexts/auth-context.js
  web/src/hooks/use-auth.js
  web/src/pages/_app.js
  web/src/pages/index.js
  web/src/pages/login.js
  web/src/pages/register.js
  web/src/utils/auth-service.js
  web/src/utils/local-storage-service.js
  web/test/pages/index-test.js
  web/test/support/mount.js
  web/yarn.lock
Labels: Front End, enhancement

#39 clean up login and register forms
  web/src/components/form-errors.js
  web/src/pages/login.js
  web/src/pages/register.js
Labels: Front End

#41 Fix Link components
  web/src/pages/login.js
  web/src/pages/register.js
Labels: Front End, bug

#42 Add some database seeds
  server/db/seeds.rb
Labels: Back End

#48 Add email to drawer and add selected value to drawer items to see where you are currently
  web/src/components/nav/drawer.js
  web/src/pages/index.js
  web/test/pages/index-test.js
Labels: Front End

#51 Update page data fetching
  web/looking-good/package.json
  web/looking-good/src/pages/index.js
  web/looking-good/src/pages/users/[id].js
  web/looking-good/yarn.lock
Labels: Front End
